### ISSUE TITLE
Generated secret too long

### ISSUE THREAD

**Issue by whsoul** [BastiaanJansen/OTP-Java#36]
hi~

thank you for your very useful library!

There are some strange stuff about SecretGenerator Class,
it generate to much long bits than expected..

I think this code is weird.

> byte[] bytes = new byte[bits * 8];

~~~java

    /**
     * Generate an OTP base32 secret
     *
     * @param bits length, this should match the length of the HMAC algorithm type:
     *             SHA1: 160 bits
     *             SHA256: 256 bits
     *             SHA512: 512 bits
     * @return generated secret
     */
    public static byte[] generate(final int bits) {
        if (bits <= 0)
            throw new IllegalArgumentException("Bits must be higher than 0");

        byte[] bytes = new byte[bits * 8];
        SecureRandom random = new SecureRandom();
        random.nextBytes(bytes);

        Base32 encoder = new Base32();
        return encoder.encode(bytes);
    }
~~~

And I have one question about Custom Key.
is it okey to generate the combination key with custom seed ( like ID, email etc ) without using SecretGenerator.class
even if bit length is matched with algorithm type

for example,
in case SHA1 - whsoul82@gmail.com_MkpBoD5YCtZi/aTS1EdEHqJneNfsw3oG4.... ( 160bit )
in case SHA256 - whsoul82@gmail.com_MkpBoD5YCtZi/aTS1EdEHqJneNfsw3oG4dqhukGy9l .... ( 256bit )

**Comment by BastiaanJansen** [comment]
Thank you, I will look into it!

Preferably, the key should be completely random. But you could generate a key based on a custom seed, it would work, but it wouldn't be as secure. But that's a trade of. May I ask why you want to add a an id / email in your key?

**Comment by whsoul** [comment]
@BastiaanJansen 
because if multi users request a OTP at the same time for emails verify, in my case, 
same master key generate same OTP with in 30sec.

so different OTP per user at the same time, need to store different generated key per email(user) or use the custom combination key ( email + generated secret )

**Comment by BastiaanJansen** [comment]
@whsoul Ah, that makes sense! Yes, that should work!

**Comment by whsoul** [comment]
@BastiaanJansen 
thank you for your feed back!

**Comment by BastiaanJansen** [comment]
@whsoul I created a new release for the secret generator fix.

**Comment by whsoul** [comment]
@BastiaanJansen 
oh, great!
I will check with new version 1.1.3
thanks!
