### ISSUE TITLE
TOTPGenerator.verify return false with valid generated otp

### ISSUE THREAD

**Issue by gvillacis-ec** [BastiaanJansen/OTP-Java#45]
Hi @BastiaanJansen I am running your example:
https://github.com/BastiaanJansen/OTP-Java/blob/main/src/test/java/com/bastiaanjansen/otp/ExampleApp.java

But when verifying the generated otp it returns false.

Attached capture:

![image](https://user-images.githubusercontent.com/51656433/128243024-509717ac-1b59-468a-917b-931dd5b63729.png)

Java 11.0.10+9 AdoptOpenJDK

**Comment by BastiaanJansen** [comment]
Hi, I just released version 1.2.2 with a fix for this bug! Thank you for notifying!
