### ISSUE TITLE
Can TOPGenerator generate an alphanumeric OTP code?

### ISSUE THREAD

**Issue by rmatute** [BastiaanJansen/OTP-Java#49]
Hi @BastiaanJansen, I was testing your example and I find it very interesting.

**I was wondering if with this I can generate an alphanumeric OTP code.?**

**Comment by BastiaanJansen** [comment]
Hi, [RFC 4226 (HOTP)](https://tools.ietf.org/html/rfc4226) and [RFC 6238 (TOTP)](https://tools.ietf.org/html/rfc6238) don't specify alphanumeric OTP codes, therefore it is not included in this library.
