### ISSUE TITLE
With the same secret Generates the same OTP code, as long as it does not expire.

### ISSUE THREAD

**Issue by rmatute** [BastiaanJansen/OTP-Java#50]
Hi @BastiaanJansen

I have a question, when I send the same secret and I want to generate an OTP code again, it generates the same as long as it is valid.

Attached capture

![issues-OTP-JAVA](https://user-images.githubusercontent.com/77020728/141509498-6f2978f7-3c62-4f2e-9710-24a7e19faa1a.PNG)

**Comment by BastiaanJansen** [comment]
Hi,

This is intended behavior, with the same secret and within the same period, the generator should generate the same OTP code.

**Comment by gvillacis-ec** [comment]
Hello @BastiaanJansen 
How should we use the OTP generator to have different OTPs each time a new one is required, considering that each OTP that is generated must have a maximum lifetime and must be able to validate within that period.

I thought that the secret could be unique and generate different OTPs with it.

**Comment by BastiaanJansen** [comment]
Hi @gvillacis-ec ,

Whenever you need a new OTP for a different use case, you must use a different secret.

For example, if you want to send an sms with an OTP-code every time a user logs in, you use a different secret for each user so if multiple users sign in, in the same period, they all receive different OTP-codes.

**Comment by gvillacis-ec** [comment]
Thanks for the explanation @BastiaanJansen
