### ISSUE TITLE
Issuer is not properly escaped in path segment of URI

### ISSUE THREAD

**Issue by svschouw-bb** [BastiaanJansen/otp-java#71]
Take the following code:
```java
byte[] secret = SecretGenerator.generate();
TOTPGenerator totp = TOTPGenerator.withDefaultValues(secret);
URI uri = totp.getURI("Acme Co", "myuser");
System.out.println(uri);
```
This will throw a `java.net.URISyntaxException: Illegal character in path at index 19: otpauth://totp/Acme Co:myuser?period=30&digits=6&secret=<secret>&issuer=Acme+Co&algorithm=SHA1`

If I escaped the issuer myself:
```java
byte[] secret = SecretGenerator.generate();
TOTPGenerator totp = TOTPGenerator.withDefaultValues(secret);
URI uri = totp.getURI("Acme%20Co", "myuser");
System.out.println(uri);
```
It outputs `otpauth://totp/Acme%20Co:myuser?period=30&digits=6&secret=<secret>&issuer=Acme%2520Co&algorithm=SHA1`
Notice the double escaping of issuer=Acme%2520Co in the query parameters.

The path section (both issuer and account) should be escaped when generating the URI.

**Comment by svschouw-bb** [comment]
Thanks for the fix!

A new version was tagged, but not released yet.

**Comment by BastiaanJansen** [comment]
Thanks for noticing! [Version 2.0.2 is now released.](https://github.com/BastiaanJansen/otp-java/releases/tag/otp-java-2.0.2)
