### ISSUE TITLE
Flexability when validating TOTP code.

### ISSUE THREAD

**Issue by brett-walker** [BastiaanJansen/otp-java#75]
From [wikipedia](https://en.wikipedia.org/wiki/Time-based_one-time_password)

`Some authenticators allow values that should have been generated before or after the current time in order to account for slight clock skews, network latency and user delays.`

Is this possible using your library to allow this flexability?

If so, could you post some code showing how this is possible.
Thanks

**Comment by brett-walker** [comment]
Looking further at the `TOTPGenerator` class.

The `public boolean verify(final String code)` method is the strict version.
The `public boolean verify(final String code, final int delayWindow)` method seems to be the more lenient version.

Would using the 2nd method mentioned able provide the flexibility I've inquired about?

**Comment by BastiaanJansen** [comment]
Yes, correct. The delay window allows you to accept codes slightly before or after.
