### ISSUE TITLE
Move Base32 to static field instead create new instance every time to generate code

### ISSUE THREAD

**Issue by DmitriyLuckyman** [BastiaanJansen/otp-java#77]
https://github.com/BastiaanJansen/otp-java/blob/4441c5e8362810144468d514c95564aa5bcfa079/src/main/java/com/bastiaanjansen/otp/SecretGenerator.java#L48

As I khow Base32 from org.apache.commons.codec.binary.Base32 is threadsafe and we can create it ones and use all time.

**Comment by BastiaanJansen** [comment]
You are correct. I released version 2.0.3 including this improvement.
